name: doom_inside_gmaps
description: Running Doom inside Google Maps.
version: 1.0.0

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  typed_data: ^1.4.0
  image: ^4.5.3
  shelf_web_socket: ^3.0.0
  shelf: ^1.4.2
  puppeteer: ^3.17.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
